### ISSUE TITLE
Implement check on 0.0.0.0 listening

### ISSUE THREAD

**Issue by nicofrand** [gelnior/pschecker#2]
Hi & thank you a lot for this, I am sure this is gonna prove useful !

In the readme we can read

> No process listens on 0.0.0.0 host: OK

But when launching `pschecker` there is only 1 check (about root password).  I guess this is yet to be implemented, this issue is just a friendly reminder.

**Comment by gelnior** [comment]
I published a new release (0.1.3) that contains that checking. Can you try it and tell me what you think about it?

**Comment by nicofrand** [comment]
Ouch indeed it works, I have a lot of apps listening on 0.0.0.0:

> Some of your servers listen to the 0.0.0.0 host.(ports: 11333, 5222, 9104, 5269, 4190)

Now that I see it, it would be really nice to also have the process' name with it as `netstat -plnt` would return for example:

```
tcp        0      0 0.0.0.0:389             0.0.0.0:*               LISTEN      2116/slapd      
tcp        0      0 0.0.0.0:11333           0.0.0.0:*               LISTEN      1715/rspamd: main p
tcp        0      0 0.0.0.0:5222            0.0.0.0:*               LISTEN      21762/lua5.1    
tcp        0      0 0.0.0.0:587             0.0.0.0:*               LISTEN      21726/master      
tcp        0      0 0.0.0.0:143             0.0.0.0:*               LISTEN      1/init          
tcp        0      0 0.0.0.0:9104            0.0.0.0:*               LISTEN      3626/node       
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      2308/nginx -g daemo
tcp        0      0 0.0.0.0:465             0.0.0.0:*               LISTEN      21726/master    
tcp        0      0 0.0.0.0:4190            0.0.0.0:*               LISTEN      21731/dovecot  
tcp        0      0 0.0.0.0:993             0.0.0.0:*               LISTEN      1/init 
tcp        0      0 0.0.0.0:5269            0.0.0.0:*               LISTEN      21762/lua5.1    
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      21410/dnsmasq   
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1961/sshd       
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      6794/smtpd    
```

By the way, `netstat -plnt` returns a lot more of apps listening on 0.0.0.0. Did you apply a filter ?

**Comment by Phyks** [comment]
@nicofrand There is a threshold on the port, it should be above 1024. See https://github.com/gelnior/pschecker/blob/master/pschecker/checks/host_listening.py#L25.

That's basically because the first 1024 ports are reserved for services running as root and that includes standard services that have to listen to 0.0.0.0 (dovecot, nginx, ssh etc).

**Comment by nicofrand** [comment]
Great ! Now I'll have to check for rspamd and others (mainly Cozy v2 I think) with yunohost if that's normal.
My dovecot is running on 5269 though.

Thanks for the tool anyway, I'm sure it will be useful to lot of people (I really can see YunoHost integrate it for example in its diagnostic tool).

**Comment by gelnior** [comment]
Yep 5269 looks to be XMPP. We should exclude it from the check.

Thanks for the command options. I will see how to include the name from them.

**Comment by gelnior** [comment]
I made the mentioned improvement: name of service listening on the wrong host and XMPP ports are now excluded. Can you try the latest release?

**Comment by nicofrand** [comment]
> Some of your servers listen to the 0.0.0.0 host: rspamd: (11333), node (9104), dovecot (4190), rspamd: (11333), mysqld (3306), dovecot (4190)

Thanks, that works great!
