### ISSUE TITLE
Host listening displays twice some processes

### ISSUE THREAD

**Issue by nicofrand** [gelnior/pschecker#8]
> Some of your servers listen to the 0.0.0.0 host: rspamd: (11333), node (9104), dovecot (4190), rspamd: (11333), mysqld (3306), dovecot (4190)

As you can see some processes are listed twice.

`sudo netstat -pltn | grep 0.0.0.0` returns `tcp        0      0 0.0.0.0:4190            0.0.0.0:*               LISTEN      8848/dovecot `
`sudo netstat -pltn | grep 0\ :::"` returns `tcp6       0      0 :::4190                 :::*                    LISTEN      8848/dovecot `

I am not sure whether the same info is displayed twice or if I misunderstand how the processes work… In the first case, maybe a de-duplication should be made to list each process only one time?

**Comment by ZeHiro** [comment]
It looks like there are several processes with the same name are running at the same time (if you look at the dovecot config of yunohost, there are several location to modify to only authorize localhost)
